### ISSUE TITLE
Reports taking too long to be generated

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1099]
**Describe the bug**
Our travis build is taking many minutes, most of them generating the test report.

**To Reproduce**
1. Start a build 
2. Wait for it to finish
3. Open logs

**Expected behavior**
It should take only 5 minutes to finish the build

**Comment by KickSeason** [comment]
When travis run the buid. It will run the unit test and generate the test report.
We have split the all culture test and coverage test to shorten the time.

One way is to perform unit tests in parallel by module. If unit test of every module takes less than 5min, we can achieve the expected behavior.

**Comment by shargon** [comment]
Take a look to this comment

https://github.com/neo-project/neo/issues/1019#issuecomment-537023894

**Comment by shargon** [comment]
Take a look to my last changes :) 
https://travis-ci.org/neo-project/neo/builds/592186030
https://github.com/neo-project/neo/pull/1136
