### ISSUE TITLE
Improve mempool UTs

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1101]
It has been emphasized that test should be each time more independent, both C# structures but also for Akka actors.

This issue is mainly focused on mempool UT, as we recently discussed at PR #1038, with @eryeer.

Some of the tests such as `TestUpdatePoolForBlockPersisted` needs to leave a transaction in the mempool and persist a block. That transaction should be later automatically verified and UT should check it at the mempool.

**Comment by eryeer** [comment]
So far I think the main problem for the global mempool is the transaction in mempool cannot be cleaned. Many tests may add transactions into the global mempool so that we cannot check changes in global mempool for each test separately.
An idea to improve the global mempool is to create a public `clear` function in `Memorypool`, which can be used to remove all the transactions from the global mempool. 
Since the unit test exection is in a single thread, we can clean the global mempool after each unit test to make the environment of the gloabl mempool clean for the next unit test.

**Comment by shargon** [comment]
I love this `clear` 🤣. I tried in the past without luck!

**Comment by Tommo-L** [comment]
Could we ask erik dalao add this method 😂

**Comment by vncoelho** [comment]
There was a PR made byn@shargon for flushing, it is an usefull feature for testing and debugging.
We could have that in different parts.

**Comment by shargon** [comment]
Not only erik, @lock9 too 😂https://github.com/neo-project/neo/pull/861#issuecomment-514020757

**Comment by vncoelho** [comment]
The point is how to design these fluxing, let's consider it as a design for testing and debugging and not as a feature to be used on operation.

**Comment by shargon** [comment]
For me a collection without Clear have no sense, maybe i want to use it in our plugin for improve neo-resilience, or maybe i want to clean the memory in my node... I don't understand why we should force the user to restart the node.

**Comment by eryeer** [comment]
> For me a collection without Clear have no sense

Agree!

**Comment by eryeer** [comment]
> For me a collection without Clear have no sense

Agree!
