### ISSUE TITLE
Gas allowance for sys_fee and net_fee (fees paid by somebody else)

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1104]
**Summary**
We need a way to make transactions 'free' again. The problem is that new users can't join the network without going through an exchange. We didn't have this problem with neo 2 because we had free tx and in other chains, you can either mine or have someone else to pay for the fee.

**Do you have any solution you want to propose?**
Contract owners should be able to pay for user else fee, using some kind of allowance mechanism.
This allowance should allow a smart contract owner to pay for the sys_fee and net_fee when some pre-authorized user is invoking his contract.
Something like `IncreaseAllowance(owner, spender, contractHash, amount)`
The ideal would be having 3 types of allowances (I think that the third one may not be possible):
`FullAllowance(owner, spender)` (any smart contract)
`PartialAllowance(owner, spender, contractHash)`  (only one particular smart contract)
`RestrictedAllowance(owner, spender, contractHash, operation)` (only one specific method from SC ABI)

(Can we reuse the witness scope concept to solve this?)

**Where in the software does this update applies to?**

- Consensus
- Ledger

**Comment by igormcoelho** [comment]
I would love this feature, free tx is a fundamental feature for broader acceptance and applications... but I don't think it is feasible anymore in this format @lock9 
@canesin had raised several critical issues on the matter, that are still holding up... one of these is that, even if contracts manage to pay tx for clients, this basic verification would have a cost (who would pay for that, if that fails?). We could manage to reduce risks and costs (see backward jump proposal), but still, requiring Storage access would always incur in non-zero costs (possibly not low). From the contract perspective, it's also hard to give fee to customers, because these customers could simply get this fee to have an opportunity to execute third-party contracts... how could the contract know which fees are actually being useful to the platform? How to manage contract costs just to setup customer free gas?

I think a much better direction involves granting this as a Consensus Node support, on Neo governance. This strategy brings zero cost to users, zero cost to contracts, only the workforce of CN and user voting with good parameters will already solve this for us in a smooth way.

**Comment by lock9** [comment]
> (who would pay for that, if that fails?)
I think this is pre-paid by the owner.  What do you mean the transaction fails? It will always be charged first, the result won't matter. If there is no allowance and no fee, the transaction won't be propagated.

@igormcoelho  in your proposal, who pays the fees?

**Comment by igormcoelho** [comment]
In the proposal #1115 only users will pay for fees, not deployed contracts. Another governance proposal we are making (together with new Consensus algorithm),allows nodes to sponsor specific contracts. This doesnt incur costs for any of the parts, and allowance would be much more strict than just gas fee (other contracts would be blocked from Entry invocation, effectively making sponsorship allowance work as expected)

**Comment by lock9** [comment]
@igormcoelho what kind of node will pay for the fee? I didn't understand it yet. For that to work, the node should participate actively in the network? 
Is there a draft of the proposal?

**Comment by igormcoelho** [comment]
@lock9 please see: https://github.com/neo-project/neo/issues/1147
