### ISSUE TITLE
implement NEP: Wallet Standard

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#112]
This NEP describes a wallet standard that allows the wallet files to be shared between the various implementations of NEO.
https://github.com/neo-project/proposals/pull/13

**Comment by BrunoFreitasgit** [comment]
Can we start on implementation or we need to wait for the acceptance of the Wallet Standard on the proposals repo?

**Comment by canesin** [comment]
@BrunoFreitasgit The proposal need to be refined, we are implementing and testing how that should look like in neon-js, take a loot in: http://cityofzion.io/neon-js/

**Comment by BrunoFreitasgit** [comment]
@canesin Okok, thanks. I'm working on a class library with only the implementation of the wallet standard (as it was on the proposal), so client-side projects made in C# only need to reference it to use it. Right now it's a separate project (and it can be transform to a nuget package for easy usage), but it easily adapted to integrate with the original neo project. Don't know if they are open for this kind of changes, so might as well post it here for they to see.
Might talk back to you in a few days to prepare a repo for CoZ review it.

**Comment by snowypowers** [comment]
I have a trial implementation of NEP Wallet on `feature/nep-wallet` in `neon-js`. [Link](https://github.com/CityOfZion/neon-js/blob/feature/nep-wallet/src/wallet/Wallet.js)

Since it is in JSON form, I made use of JS features (basically `JSON.stringify` and `JSON.parse`) so it was really simple. There is not much functionality attached to the Wallet object, most of the functionality is concentrated on Account. 

**Notes:**

1. We might want a versioning for the Wallet for future-proofing.
2. `name` is used for wallet name but `label` is used for Account. Could be consistent with a single name.
3. Do we want to set max/min for scrypt parameters? Some libraries have them. For example, [js-scrypt](https://github.com/tracker1/node-js-scrypt)
