### ISSUE TITLE
Support cross language plugins

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1225]
**Summary**
Today, you can only build plugins for the mainnet version of neo in C#. As part of Neo's general multi language strategy, it would be nice for developers to be able to build plugins in whatever language they choose.

**Do you have any solution you want to propose?**
VSCode has the exact same issue with their language servers and debuggers. VSCode is implemented in typescript, but it needs to support language servers and debuggers written in any language. Microsoft has defined a JSON-RPC style protocol [debug adapters](https://microsoft.github.io/debug-adapter-protocol/overview) and [language servers](https://microsoft.github.io/language-server-protocol/overview) that communicates processes built in different languages over network sockets or [standard IO](https://en.wikipedia.org/wiki/Standard_streams). 

I propose we do something similar for at least some of the Neo plugin types

**Where in the software does this update applies to?**
- Core

**Comment by roman-khimov** [comment]
This kind of technology would actually be nice for neo-go development too. [Go's support for plugins](https://golang.org/pkg/plugin/) is very limited, so at the moment we're bringing equivalents to many C# plugins right into our core codebase. For some plugins that's fine, because we may think that they should be core functionality anyway (because of the value they provide), but at the same time there are a lot of plugins that we wouldn't like to reimplement or bring into the main repository.

Having plugins interacting with the node via some kind of streaming interface would allow us to reuse C# plugins directly, if and when there is a need to. So it's not just about C# node using X-language plugins, it's also about X-language nodes (hey, there should be more node implementations in different languages!) reusing C# plugins.

And it shouldn't be that hard to do, we already have this APIs defined in the C# code, so it's just a question of specifying them in JSON-RPC (or gRPC, or...) and changing the node a little bit.
