### ISSUE TITLE
[Oracles] Economic Model

### ISSUE THREAD

**Issue by belane** [neo-project/neo#1279]
Discussion of the pricing and reward model for the Oracle system.
We must also cover possible penalties for malicious nodes.

This topic is closely linked to oracle policy https://github.com/neo-project/neo/issues/1277

**Comment by doubiliu** [comment]
Cost model
Since the size of return data is limited,we can compute fee by the invoke counts. 
Oracle Fee=Request count * perRequestFee

Incentive model
It is hard punish malicious nodes.Because there is not a effect way to prove oracle return a wrong 
data when it access a URL. So penalties maybe is not necessary.

And Oracle Fee can be assigned to Oracle nodes on average if we do not consider Freeload problem .This can avoid evil Speaker.

**Comment by shargon** [comment]
Also we need to define the payment method. We need a new gas field?

**Comment by doubiliu** [comment]
A simple way is define a new field `OracleFee `in tx. And it will be a  key paremter  to limit the request count when VM executes a script.

**Comment by erikzhang** [comment]
Is Oracle fees fixed?

**Comment by doubiliu** [comment]
Oracle Fee=Request count * perRequestFee

**Comment by erikzhang** [comment]
If perRequestFee is fixed, we don't need an extra field. We can calculate it easily and mix it with `NetworkFee`.

**Comment by doubiliu** [comment]
If mix it with NetworkFee,speaker should commit Oracle transaction preferentially.

**Comment by doubiliu** [comment]
And if we use `NetworkFee` ,we can not limit request count in vm.

**Comment by erikzhang** [comment]
Do you mean "retry"?

**Comment by Tommo-L** [comment]
> We can calculate it easily and mix it with NetworkFee

A precondition is required,  consensus node's address is the oracle node's address. 

Using `OracleFee`,  it can help to limit the count of oracle requests in vm (as the oracle fee is not contained in `sysfee`), when the oracle tx executed on chain. And it's easier to calculate dividends.

**Comment by erikzhang** [comment]
Do we allow multiple requests in a single transaction? Or do we only allow one request with multiple retrying?

**Comment by erikzhang** [comment]
I think the easiest way is to add the fields to `OracleRequest`.

https://github.com/neo-project/neo/blob/64c30a8cbd8a6646deddc00db5d50223a86d42da/neo/Oracle/OracleRequest.cs#L5

**Comment by shargon** [comment]
> Do we allow multiple requests in a single transaction? Or do we only allow one request with multiple retrying?

Yes, but if it is to the same resource, it will take the cached result for the second request. Only one request will be done to internet.

**Comment by shargon** [comment]
I think that retry is more related to the own node policy, if he know that his network is unstable, maybe he need to retry the request, otherwise not.

**Comment by doubiliu** [comment]
I think it is necessary to allow multiple requests in a Oracle transaction.Since the logic of smart contract is flexible,user will have demand to multiple invoke Oracle service in one Oracle transaction.(Of course,contain 'retry').We should not limit these demand.

**Comment by doubiliu** [comment]
Well,let's do some summary:

**Cost model**
I think the size of return data will have a max value,so we can calculate costs based on the invoke counts.
`Oracle Fee`=`Request count` * `perRequestFee.`
 `perRequestFee.` is a fixed value and will be setted in native contract.
`Request count`  is a dynamic value and will be setted by user according to his demand.
And `Oracle Fee` maybe as a field in TX well.I don't know the logic of 'OracleRequest',so I can't confirm whether it is appropriate.

*Of course,we can limit that one TX can only have one request.But I think it will reduce the flexibility of smart contracts.

**Incentive model**
As mention above,it is hard punish malicious nodes.So designing a penalties model is difficult.
Distributed fee evenly to all Oracle nodes maybe is  a simple and effective way if we can tolerate some little evil,such as freeload.

But we still need design some mechanism to avoid obvious attack.`Oracle Fee` is an important field.Since to system it is hard to know the actual request count before the script has been executed.To avoid free request,I think we need some limit.

We can use `OracleFee` to limit actual request count.We need a little change on VM code.
When VM load a script,it will record the max request count.And every time script invoke a Oracle Service, the value will minus one.If value==0,Oracle Service will not work and return fault directly.
This can avoid free request effectively. 

![image](https://user-images.githubusercontent.com/42929757/70019012-e3541a80-15c2-11ea-814c-3e085a578f5e.png)

**Comment by doubiliu** [comment]
@shargon @belane @erikzhang do you have some comments and suggestions？

**Comment by belane** [comment]
It looks good. I agree with you, we should allow more than one request for smart contract/invocation.

We can talk about all the limits we need in https://github.com/neo-project/neo/issues/1260

**Comment by shargon** [comment]
Now that we decided the two TX model, we need to define the economic model. I made this proposal https://github.com/neo-project/neo/pull/1579

- SysFee it's for oracles (request and response) goes to Oracle multisig if it has less than X otherwise it will be distributed for oracle nodes.
- User will pay for the response extra cost.
- User will pay for the filter cost.
- It should have an additional extra cost (TBD)

**Comment by erikzhang** [comment]
Do we have a native oracle contract? Maybe we should remove the SYSCALL and change it to a method of the contract. Then the fee can be sent directly to this contract. So there is no need to deduct from sysfee.

**Comment by shargon** [comment]
> Do we have a native oracle contract?

Yes

> Then the fee can be sent directly to this contract

you mean listening the notifications?

**Comment by erikzhang** [comment]
Yes.

**Comment by erikzhang** [comment]
Or even the oracle contract can transfer the fee from the sender's account automatically.

**Comment by shargon** [comment]
But the response it's persisted before the request, in the request its located the fee, and for taking this fee we need the oracle multi signature.

**Comment by shargon** [comment]
If we check the notifications when user consume the downloaded data, if the user tx fault, oracles won't be rewarded.
