### ISSUE TITLE
Update Akka to up-to-date version

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1455]
According to https://github.com/akkadotnet/akka.net/issues/2378#event-3071191410 there might be benefits in the P2P on the last version.

As #611 mentioned and discussed in other threads.

![image](https://user-images.githubusercontent.com/17395762/75457497-4ef81a80-595b-11ea-8814-368d4eb04b43.png)

**Comment by ShawnYun** [comment]
That sounds good.

**Comment by shargon** [comment]
Good news :)

**Comment by ShawnYun** [comment]
Major changes from akka 1.3 to akka1.4 include:

**1.Akka.Remote's performance has significantly increased as a function of our new batching mode- which is tunable via HOCON configuration to best support your needs.**

  The default transport in Akka.Remote is the DotNetty TCP transport, which is a good choice for most Akka.NET developers because TCP preserves message order and guarantees delivery of every message over the wire so long as the network remains available, which is consistent with IActorRef default messaging. The same cannot be said for alternative transports such as a UDP transport.
    As of Akka.NET v1.4.0-beta4, we've added a new feature to Akka.Remote called a "batch writer" which has tremendously improved the performance of outbound writes in Akka.Remote by grouping many logical writes into a smaller number of physical writes (actual flush calls to the underlying socket.)
    Here are some performance numbers from our RemotePingPong benchmark, which uses high volumes of small messages.
    These numbers were all produced on a 12 core Intel i7 2.6Ghz Dell laptop over a single Akka.Remote connection running .NET Core 2.1 on Windows 10:
![](https://user-images.githubusercontent.com/42930111/76055549-e5a58680-5fae-11ea-88c0-59a01c3deec6.png)
![](https://user-images.githubusercontent.com/42930111/76055552-e6d6b380-5fae-11ea-99e0-e5d58e069b85.png)
    **It can be seen that the average performance after improvement is 141,091 MSG /s, which is 1.7 times higher than before. The standard deviation was 15,291 MSG /s, indicating that the stability of the new akka was greatly enhanced。**
Akka.Remote's flush batching system for DotNetty operates on the principle of trying to minimize the number of system calls to the I/O system because they are (1) expensive and (2) unpredictably long-running. Our data shows grouping together dozens of small writes, ~218 bytes per message in this sample, into larger payloads in the 4kb range significantly reduces the standard deviation for this benchmark, significantly improves the average, and also increases the maximum absolute throughput observed.
```
akka.remote.dot-netty.tcp{
      batching{
        enabled = true
        max-pending-writes = 30
        max-pending-bytes = 16k
        flush-interval = 40ms
      }
}
```
The batching system inside the DotNetty TCP transport works using the following business rules.
Only flush to the underlying transport when one of these happens:
1.	batching.max-pending-writes - When 30 total messages, irrespective of their size, are queued for writing - flush the batch immediately upon receiving the 30th write;
2.	batching.max-pending-bytes - When 16kb worth of messages have been queued, regardless of the number of messages, flush the batch immediately;
3.	batching.flush-interval - If neither of the two previous conditions have been met flush whatever is waiting inside the queue for this connection within 40 milliseconds.
you can disable batching via akka.remote.dot-netty.tcp.batching.enabled = false.

**2.All HOCON Config objects have been moved from the Akka.Configuration namespace within the core Akka library to the stand-alone HOCON project and its subsequent HOCON.Configuration NuGet package.** 
So we need to 
1. Change all Akka.Configuration.Config calls to Hocon.Config and
2. Add using Hocon; statements to wherever you work with HOCON directly.

**Conclusion:** 
Akka1.4 has many improvements, but the two most important ones for NEO are the above. 
After upgrading to 1.4, the overall performance and stability of the system will be greatly improved.

**Comment by vncoelho** [comment]
Great compilation @shawnyun, could you proceed with the PR?

**Comment by ShawnYun** [comment]
@vncoelho Yes, I will test it and send the PR.

**Comment by Tommo-L** [comment]
Waiting for a more stable version https://github.com/akkadotnet/akka.net/issues/4329#issuecomment-599381429
