### ISSUE TITLE
Is p2p compression worth it?

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1905]
I made some tests with the p2p compression, comparing Gzip with Lz4, the winner it's Lz4, but i am not sure if it's worth

At first my test was focused on random binary data ... And I can't achieve valid compression with random data, always the output was greater than the input. 
Then I changed a bit to use a Transaction object, but to create a large one I used a script with random data ... and now some of it was compressed, but a little bit, 20 bytes ... more or less ... And now I think it is not worth compressing the p2p message if it contains binary data ... we will spend more time in compression than sending the raw packet ... 

![image](https://user-images.githubusercontent.com/3167973/92140451-6683f480-ee11-11ea-9ea2-ee35b7384258.png)

This is my code:

```csharp

        private static byte[] CompressGzip(byte[] input)
        {
            using var result = new MemoryStream();
            var lengthBytes = BitConverter.GetBytes(input.Length);
            result.Write(lengthBytes, 0, 4);

            using (var compressionStream = new GZipStream(result, CompressionLevel.Optimal))
            {
                compressionStream.Write(input, 0, input.Length);
                compressionStream.Flush();

            }
            return result.ToArray();
        }

        private byte[] CreateTransactionWithSize(int v)
        {
            var rand = new Random();
            var r = new Random();
            var tx = new Transaction()
            {
                Attributes = System.Array.Empty<TransactionAttribute>(),
                Signers = new Signer[] { new Signer() { Account = UInt160.Zero } },
                NetworkFee = 0,
                Nonce = (uint)Environment.TickCount,
                Script = new byte[0],
                SystemFee = 0,
                ValidUntilBlock = (uint)r.Next(),
                Version = 0,
                Witnesses = new Witness[0],
            };

            // Could be higher (few bytes) if varSize grows
            tx.Script = new byte[v - tx.Size];
            r.NextBytes(tx.Script);
            return tx.ToArray();
        }

        [TestMethod]
        public void T()
        {
            var maxIterations = 100;
            var dicLz4 = new Dictionary<int, Rate>();
            var dicGzip = new Dictionary<int, Rate>();

            for (int size = 128; size < 10_024; size += 128)
            {
                var rateLz4 = new Rate();
                var rateGzip = new Rate();

                for (int iterations = 0; iterations < maxIterations; iterations++)
                {
                    var b = CreateTransactionWithSize(size);
                    var c = Neo.IO.Helper.CompressLz4(b);

                    if (c.Length < b.Length)
                    {
                        rateLz4.Threshold += b.Length - c.Length;
                        rateLz4.Less++;
                    }
                    else
                    {
                        rateLz4.More++;
                    }

                    c = CompressGzip(b);

                    if (c.Length < b.Length)
                    {
                        rateGzip.Threshold += b.Length - c.Length;
                        rateGzip.Less++;
                    }
                    else
                    {
                        rateGzip.More++;
                    }
                }

                if (rateLz4.Less > 0) dicLz4[size] = rateLz4;
                if (rateGzip.Less > 0) dicGzip[size] = rateGzip;
            }

            // BreakPoint
        }
```

We should specify when we want to try compress the message or not? I think that yes.

**Comment by roman-khimov** [comment]
Well, random data won't compress, that's expected. But we have some not-so-random areas where it can be effective.

The logic that we use in neo-go to determine whether to compress things or not differs a little from C# node. We never compress some types of payloads (Headers, MerkleBlock, Null, but thinking a bit more Inv and GetData should probably also be there), they mostly contain hashes inside and hashes just don't compress. We then of course also look at the size of the payload, but we're triggering compression only from 1024 bytes instead of 128 (because one packet communication cost is very similar irrespective of its size and if compression doesn't save us some packets it's almost useless). And when we compress --- we compress, we don't have anything analogous to `CompressionThreshold`.

But of course all of this is opinionated and technically requires a lot of experimentation and fine-tuning. There is a cheaper thing we can do though --- just try disabling compression completely and see if it affects four nodes benchmark results in any way.

**Comment by shargon** [comment]
Could you specify what payloads do you try to compress? we should unify this rules. @roman-khimov

**Comment by roman-khimov** [comment]
> Could you specify what payloads do you try to compress?

Basically, anything not blacklisted (Headers, MerkleBlock, Null) with a size of more than 1024 bytes.

> we should unify this rules.

It's not strictly required. Both sides support compression but both sides may not use it as well sending uncompressed payloads, it doesn't affect interoperability.

**Comment by shargon** [comment]
> we compress, we don't have anything analogous to CompressionThreshold.

I think that `CompressionThreshold` it's important, if you will send only 2 bytes less, the remote node will spend more time in decompress than the benefit of the network.

**Comment by roman-khimov** [comment]
That's correct, but given our initial type filters we are betting that the rest of payloads compress good enough. Or we're just being lazy and try to avoid the question of what this `CompressionThreshold` or `CompressionRatio` should be, because it also is not that simple.

Type filtering isn't perfect too, BTW. We have consensus payloads and under load we'll have huge PrepareRequest messages that will mostly consist of hashes, so they won't compress a lot, but it's the same consensus payload for PrepareRequest as for  PrepareResponse or other messages.

And compression effectiveness also depends on other protocol properties, like we can only send one transaction in one message now. A typical invocation is ~250 bytes, so C# node will try compressing it, but either won't get enough benefit from it (`CompressionThreshold`) or will get some and send it compressed saving ~70-80 bytes. NeoGo won't bother compressing it at all. But if we're to have an ability to send multiple transactions in one payload (batching), the picture will change a lot, the size of the payload is going to be bigger and it will have way more duplication inside for compression to be more effective.
