### ISSUE TITLE
Is it necessary to check admin signature in the  `SetAdmin`  in NameService? 

### ISSUE THREAD

**Issue by doubiliu** [neo-project/neo#2274]
Currently,we will check admin and owner signature in the  `SetAdmin`  in NameService.
Is double check redundant?

**Comment by erikzhang** [comment]
The administrator is legally responsible for the domain name, so you must get his consent to make someone an administrator.

**Comment by doubiliu** [comment]
But the owner has legal ownership of the domain name, and the administrator is just a delegation.

**Comment by bettybao1209** [comment]
![image](https://user-images.githubusercontent.com/12050350/106230702-1035a900-622b-11eb-98c5-a8386a80d40f.png)
![image](https://user-images.githubusercontent.com/12050350/106230843-5a1e8f00-622b-11eb-8b1d-ab31b57c53a9.png)
Here I invoked the `SetAdmin` method to set the `NUjGMLwcYZuhUSTeNcZSvYkrQRciAh` as the admin, and it failed to relay the tx since the insufficient network fee of the tx that needs to be signed be two different wallets .  Should the admin be the multisig address?

**Comment by shargon** [comment]
I think that admin it's not needed, we can transfer the ownership, and remove admin

**Comment by doubiliu** [comment]
@shargon 
I think admin still need to exist. The separation of ownership and management is necessary. Just as the current Internet domain name can belong to private or company, but the domain name is often managed by IT engineer. You can't let the boss set up the domain name white list, right?:)

**Comment by shargon** [comment]
Then we can use admin or owner, but no both of them https://github.com/neo-project/neo/pull/2280
