### ISSUE TITLE
Free TXs with Proof-of-Work

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#2465]
@shargon @igormcoelho 
As we intensively discussed in the past for NEO2, we had a system with a Quota for Free txs ordered by Proof-of-Work (hash of the transactions).

I still believe it is quite important for N3 to have a space for free txs, or at least, keep a quota that is ordered by Hash (on the other hand, establishing that quota would be similar as a free txs quota).

**Comment by shargon** [comment]
I think that it's a good option for avoid the spam

**Comment by vncoelho** [comment]
We can even establish a limit that will deny txs. The difficulty increase as the % reserved to free txs increase.

**Comment by hal0x2328** [comment]
If someone wanted to attack the network with free PoW transactions, could they prepare and hash transactions over a long period of time, then wait and relay them all at once? Is there some aspect to the proposed PoW algorithm that prevents them from hashing transactions well in advance of the relay time? Like incorporating the hash of a recent block and then the transaction is rejected if that block is more than N blocks ago?

**Comment by vncoelho** [comment]
That is a great point @hal0x2328.
We could add such a necessary extra field on the transaction!

**Comment by roman-khimov** [comment]
Creating hash competition on Neo just doesn't sound right to me, regular people won't do that so their transaction hashes will be random and it'd be easy to kick such transactions out of the pool.

Free transactions bring more trouble than they solve. There are several approaches to how transactions can be sponsored and I think that's the way to go.

**Comment by vncoelho** [comment]
> Creating hash competition on Neo just doesn't sound right to me
Historically, NEO 2 had this feature and we are now removing it.

The main discussion is on how to improve it, like on the way @hal0x2328 just pointed out.

I believe that sponsored are a good feature as well, in particular, we have been pushing and defending it for years.
But one does not block the other, which are different.

**Comment by lock9** [comment]
I cannot be more against such a feature. Can't we see what is happening around the world? While every platform is trying to distance itself from PoW due to its environmental impacts, we are considering adding it to Neo? Come on guys, it is like going back to coal in 2021. Not only that. There is no such thing as free transactions. The difference is that people would be paying computer parts manufacturers instead of Neo holders. Nothing is free.

I'm absolutely not in favor, as this is against all current trends, bad for holders and bad for the environment.

**Comment by vncoelho** [comment]
Environmental impacts, @lock9?
My PhD was in Renewable Energy and I do not see those complaining about it pushing good resources to be used by electric cars (which use energy generated from where?).
A real transition comes with microgrids becoming really decentralized and the energy economy changes towards autonomous systems that interact on a given infrastructure.

Previously, the PoW of Neo is used to order transaction. This a minor PoW for spam protection, it is not for safety of the system like Bitcoin, completely different scenario.

**Comment by roman-khimov** [comment]
> This a minor PoW for spam protection

I don't see how it protects from spam. Regular people don't own mining rigs, so they will try creating and sending free transactions as is without any attempts to create some better hash (as they do now on Neo Legacy). Meanwhile anyone with enough hardware will just spam the pool with "properly hashed" transactions and kick out anything coming from people that didn't even try to prove their work (I think we're just lucky that it doesn't happen on Neo Legacy at the moment).

**Comment by roman-khimov** [comment]
So to me the model of "no gas --- no spam" is more reliable and it's simpler. Actually, that was one of the questions for NeoFS sidechain, whether we want to make an option to support free transactions there. Technically its internal GAS is worthless and we just need transactions to be accepted, fees don't make any economical sense there, but still we decided to keep things as they are and not introduce free transactions. Exactly because controlling GAS distribution on this network reliably protects it from spam (and other things like #2427).

**Comment by hal0x2328** [comment]
I think this approach has potential in the case where an address has been sent NEO but they have no GAS to send it out again and receive their claimable GAS for the first time. 

So this PoW addition would help new users in that case. If they already have GAS they shouldn't need free transactions. It's getting it the first time that is tricky because of the chicken-and-egg problem created by a dual-token system with no free transactions (as demonstrated by Ontology).

Also PoW is a charged term now due to environmental concerns, maybe it should be called a "lengthy calculation" instead. It's in no way comparable to Bitcoin or other PoW applications because there is no real financial incentive to hash these edge-case transactions.

**Comment by EdgeDLT** [comment]
> I don't see how it protects from spam. Regular people don't own mining rigs, so they will try creating and sending free transactions as is without any attempts to create some better hash (as they do now on Neo Legacy).

Indeed, this seems to be the case in practice. Nano is a cryptocurrency with no fees which relies purely on PoW to prevent spam. It's a good network with a novel philosophy (no block incentives at all) but as you would expect, one malicious actor is all it takes to saturate and block for normal users. In recent months especially the network has had a lot of difficulties, prompting a [new design](https://forum.nano.org/t/election-scheduler-and-prioritization-revamp/1837) they hope will remove the need for PoW mitigation.

I think L2 is our best hope for sustainable free transactions.
