### ISSUE TITLE
You can get FAULT transactions with GetTransactionForContract

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#2579]
**Summary or problem description**
Currently if you call `GetTransactionForContract` you can't know if the transaction was successful or don't, it's mandatory to know the result of the execution, o return null if the transaction was fault.

https://github.com/neo-project/neo/blob/7e2d435aada96e7e22c7564984bff1419377c33f/src/neo/SmartContract/Native/LedgerContract.cs#L226

**Do you have any solution you want to propose?**
- Return null or FAULT.
- Add another syscall.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- Ledger

**Comment by roman-khimov** [comment]
I don't think return `null` would be appropriate, because transaction in question does exist in the Ledger and it's traceable, so it should be returned. At the same time its execution status and side-effects are important, that's true, which reminds me of #2034. I'd probably go for additional API to get execution status/notifications/things like that.
