### ISSUE TITLE
ApplicationEngine and events

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2869]
So im running a full node syn-ed up to latest. How can i reverify a transaction? So i can get the notifications from it. I tried something like this

### _example_

```CSharp
using ApplicationEngine engine = ApplicationEngine.Create(TriggerType.Application, tx, snapshot, block, system.Settings, tx.SystemFee);
engine.LoadScript(tx.Script);
```

Now the problem im running into, is that when a contract is already deployed and the transaction deploys the contract. I get an error saying contract exists. The reason i want to reverify is to get the notifications of the transaction. I know i can get runtime information by doing the following.

```CSharp
ApplicationEngine.Notify += OnApplicationEngineNotify;
Blockchain.Committed += OnBlockchainCommitted;
Blockchain.Committing += OnBlockchainCommitting;
```

but i want to requery the notifications, just in case i missed one or want to look at old transactions. 

### How can i can do this?

**Comment by roman-khimov** [comment]
Take a look at [ApplicationLogs plugin](https://github.com/neo-project/neo-modules/tree/master/src/ApplicationLogs), it stores transaction notifications (among other things) after execution so that you could retrieve them later. Usually it's done via `getapplicationlog` RPC.

**Comment by cschuchardt88** [comment]
@roman-khimov 
Thanks for the time to answer me. 

i'm doing that now atm with my custom mapping and lookup in leveldb for blockchain events. Its slow a long process for loading the whole blockchain on testnet, about 100,000 blocks have max transactions on it. Also im using my own custom node. 

The previous comments' example works great for 99% of all transactions, Just not for the ones that have the event deploy, since the contract is already deployed.

**Comment by roman-khimov** [comment]
The `ApplicationEngine.Create()` approach will fail in a lot of other scenarios as well, please don't rely on it. The problem is the `snapshot` you're giving it, it'll be some current state of the blockchain, while in fact transaction was executed some N blocks ago with a different state of the blockchain. It may seem to work in some cases, but in general this is just wrong. You either need to store/retrieve these logs as is (with `ApplicationLogs` or some custom code if you're already doing something in the node) or try doing some "historic" invocation (like [what NeoGo provides](https://github.com/nspcc-dev/neo-go/blob/master/docs/rpc.md#invokecontractverifyhistoric-invokefunctionhistoric-and-invokescripthistoric-calls)), but even that won't be perfect since blocks have their own execution contexts (pre/post transaction processing) and you may have a number of transactions in a block.

Once upon a time I've drawn these:
<img width="719" alt="Screenshot_20230612_182656" src="https://github.com/neo-project/neo/assets/22092804/cabcbcf9-fa9f-43ae-ae17-1437f0056053">
<img width="659" alt="Screenshot_20230612_182731" src="https://github.com/neo-project/neo/assets/22092804/7443d584-5bbd-435f-bf0a-becc5dd520cf">

Maybe you'll find them helpful.

**Comment by cschuchardt88** [comment]
@roman-khimov 
thank again I think i found a bug as well. Or is this normal behavior?

### Your code
```CSharp
protected virtual void OnSysCall(InteropDescriptor descriptor)
{
    ValidateCallFlags(descriptor.RequiredCallFlags);
    AddGas(descriptor.FixedPrice * ExecFeeFactor);

    object[] parameters = new object[descriptor.Parameters.Count];
    for (int i = 0; i < parameters.Length; i++)
        parameters[i] = Convert(Pop(), descriptor.Parameters[i]);

    object returnValue = descriptor.Handler.Invoke(this, parameters); // <-- this line
    if (descriptor.Handler.ReturnType != typeof(void))
        Push(Convert(returnValue));
}
```

### StackTrace
```
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Neo.SmartContract.ApplicationEngine.OnSysCall(InteropDescriptor descriptor)
   at Neo.SmartContract.ApplicationEngine.OnSysCall(UInt32 method)
   at Neo.VM.ExecutionEngine.ExecuteInstruction(Instruction instruction)
   at Neo.VM.ExecutionEngine.ExecuteNext()
```

### Unit Test (this on fully syn-ed testnet)
```CSharp
void Test_Transaction_Scripts()
{
    var tx = NativeContract.Ledger.GetTransaction(_system.StoreView, UInt256.Parse("0xff15c584e31bd4f530d04f5cecabcb1bd157c10306ee028b564c1944150c7891"));
    var block = NativeContract.Ledger.GetBlock(_system.StoreView, 0);  //CreateDummyBlock(_system.StoreView, ProtocolSettings.Default);
    var contract = NativeContract.ContractManagement.GetContract(_system.StoreView, UInt160.Parse("0x0313bdad26721ae6867df516139d4e52f749f360"));
    using var app = ApplicationEngine.Create(TriggerType.Application | TriggerType.Verification, tx, null, _system.GenesisBlock, settings: ProtocolSettings.Default);
    app.LoadContract(contract, contract.Manifest.Abi.GetMethod("sayHello", -1), CallFlags.ReadOnly | CallFlags.AllowNotify);
    app.LoadScript(tx.Script);
    app.Execute();
            
    Console.WriteLine();
}
```

### note i debugged the test and inspect "app" variable and look at "FaultException"
