### ISSUE TITLE
What are the NEO Foundation/NGD's overarching purpose, goals, objectives & drivers for the NEO 3.0 Release? ...both business and technical

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/neo#294]
To: @dahongfei, @PeterLinX, @lerider, @erikzhang:

What is the theme for the NEO 3.0 Release?

More specifically, what are NEO Foundation/NGD's overarching:
- purpose (business and technical),
- goals (business and technical),
- objectives (business and technical), and 
- drivers (business and technical)

for the NEO 3.0 Release?

**Comment by erikzhang** [comment]
What is business?

**Comment by f27d** [comment]
In the pursuit of being helpful here.
We can expand on business to mean economic and ecosystem:
- For example, is there expected to be an impact on existing businesses/orgs/projects that are using NEO as well as the community (developers and users) because of changes to NEO 3.0 that are intended (or unintended) as results of these changes

We assume NEO 3.0, which looks like it covers many things, will have an impact on the ecosystem around it which will impact things like number of transactions, number of dapps, number of NEP-X tokens and also impact the developers, their tools and generally businesses and their decision to use or not use NEO.

Ultimately these things will drive the market value of NEO and its ecosystem that builds on top of it.

Hope that's helpful Erik.

**Comment by erikzhang** [comment]
I'm not the NGD guy. @PeterLinX

**Comment by mwherman2000** [comment]
I'm updated the title

**Comment by PeterLinX** [comment]
@mwherman2000 
NGD is an execution organization of NEO Foundation, it mainly focus on basic infrastructure of NEO ecosystem. It's a non-profit organization, so the purpose, goals, objectives and drives are the same, which is to make NEO a better smart contract platform and to develop NEO ecosystem.

**Comment by localhuman** [comment]
This is not really a forum for discussion of non-software related topics.

**Comment by mwherman2000** [comment]
These goals/objectives/drivers is what should be driving these software discussions but just like the NEP-5  discussion, the Gang of Zion is again shutting down another important discussion.

**Comment by jonatanblockchain** [comment]
@localhuman NEO is a open community. Discussions if done with respect and education are welcome, In any case, IMO the person responsible for closing the discussion (on neo-project) is Erik or Peter. I suposse you have reached an agreement with the other members of the Coz Council before closing.

In the end if Michael starts this discussion it is because like everyone we are very proud of NEO and we want NEO to success, and sometimes we would like to have more information/comunication.

So, let's leave this discussion closed and focus on how to improve NEO.

**Comment by mwherman2000** [comment]
#nomorewalledingatedcommunities #nomorewalledingateddiscussions #nomorecensureship

**Comment by mwherman2000** [comment]
The answers to the questions are critically important inputs into The NEO 3.0 Economic Model (https://github.com/neo-project/neo/issues/289) until they were shutdown/shutout/censored by the Gang of Zion.

**Comment by mwherman2000** [comment]
@peterlinx @erikzhang Reopen the issue unless the NEO Foundation/NGD is also supporter of this style of censorship that has become a common practice of the Gang of Zion.

Cc: @dahngfei @lerider

**Comment by mwherman2000** [comment]
#RIP This isn't worth my personal time. Just like NEP-5.

**Comment by erikzhang** [comment]
The only thing the Neo Foundation does is spend money and make sure that it is spent in places that can enhance Neo ecosystem.
In this process, there are a lot of specific work to be done, and that is the responsibility of NGD. NGD is the executive body of the Neo Foundation.
Specifically to NEO 3.0, both the Neo Foundation and the NGD, their responsibilities are unchanged.
NEO is an open community where every participant can make its own contribution to the community. As a founder, I do not mean that I have more power than any of you, and that I do not own this project. Neither the Neo Foundation nor NGD owns the project. The project belongs to the community, so every member of the community should be able to influence NEO's future development.
Because of this, we need to explore, not quarrel. GitHub is a place for collaborative development and discussion of technology, and I want everyone to focus on that.

@mwherman2000 I'll lock this post first. If you think it is necessary to continue the discussion on the original question, please open a new post.
