### ISSUE TITLE
WebSocket in `NeoSystem` doesn't work

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3038]
**Describe the bug**
the `wsport` port number  `10334` has never worked for me. At 1st I thought it was my lack of knowledge of the Network Protocol. But it turns out since I started creating my own node. It useless code that doesn't run or work. You can't use `akka` with `asp.net` websockets. Akka **doesn't** support or talk in websocket protocol language.

**To Reproduce**
1. Use something like `Postman`
2. Connect to the node on port `10334`

**Expected behavior**
Should function as a binary websocket.

**Screenshots**
![image](https://github.com/neo-project/neo/assets/8141309/62fb2df8-6661-4671-a0ca-8ac324235ff5)

**Platform:**
 - OS: win11
 - Version 3.6.2

**Comment by Ashuaidehao** [comment]
After some test, Akka's context couldn't use in `aysnc/await` directly, it will throw an exception of `There is no active ActorContext, this is most likely due to use of async operations from within this actor.` in this line.
https://github.com/neo-project/neo/blob/254fc9935f82d5c18d1a1c3c6e3b74a0515f8bd4/src/Neo/Network/P2P/Peer.cs#L396
So our websocket channel has never been enabled. 
Since we have TCP channels for P2P message forword, the websocket channels looks no use any more.

**Comment by cschuchardt88** [comment]
If you remove it, than maybe we can convert to `dotnet standard 2.1`. The main reason why we couldn't do this, is because of the `asp.net core` part. 

Does that mean we are not fixing or removing it?

**Comment by roman-khimov** [comment]
I've never seen it being used, NeoGo never supported it (and no one ever requested it), so if it doesn't work anyway, it can be safely removed.

**Comment by vncoelho** [comment]
Perhaps Akka has its internal mailbox, if the rest can be removed it would be a good move.

**Comment by Jim8y** [comment]
Wait a minute, if we support it, will it improve the performance?

**Comment by cschuchardt88** [comment]
>Wait a minute, if we support it, will it improve the performance?

No, If anything it will slow the node down. All you have is same number of connections. Just split up unevenly on different ports.
