### ISSUE TITLE
Add "GetUnspentCoins" to RPC

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#331]
Hello,

In order to remove our dependency from NeonDB and neoscan, I suggest we add an RPC call to get the unspent coins. 
What is the reason to have this feature hosted outside the nodes?

**Comment by saltyskip** [comment]
See discussion here #150 . It is reccomended that this be implemented as a plugin due to large storage requirements that would be necessary on a node to host all of this data.

I'd love to see an official tutorial on integrating plugins onto a NEO node @erikzhang, is that material available somewhere?

**Comment by erikzhang** [comment]
This can be implemented in a plugin now.

You can see the tutorials at https://github.com/neo-project/neo-plugins
