### ISSUE TITLE
Introduce single working title that covers all progression surrounding NEO 2.x (e.g. NEO Lighthouse)

### ISSUE THREAD

**Issue by deanpress** [neo-project/neo#333]
This post is an elaboration of my comment made in the NEO 3.0 Genesis Block Issue: https://github.com/neo-project/neo/issues/327#issuecomment-409374487

# Updated proposal:
Referring to my comment: https://github.com/neo-project/neo/issues/333#issuecomment-412066474

I propose we assign a working title to all updates/progressions surrounding NEO 2.x (NEPs, features, fixes), and give it a specific project name e.g. **_NEO Lighthouse_**

The project title can serve as a "parent milestone" for everything affecting NEO 2.x.

It relates to all updates, roadmap items, and NEPs that are not exclusive to NEO 3.0.

For example, the next major neo-core update (2.7) plus a batch of NEPs being merged could indicate the "launch" of the milestone.

**This opens up a lot of opportunities in terms of marketing, branding, and communication.**

It also satisfies developers' desires surrounding NEO semanic versioning, and community desires surrounding current progress in both development and marketing. It would bring attention to the right (read: current) things. "NEO 2 years in the future" got branded and recognized by the community, presently leaving uncertainty with "NEO in the present". The latter should now have an opportunity to be re-recognized and branded.

Additionally, NEO 3.0 could later have a project name like **_NEO Captain_** or **_NEO Starboard_**, following the theme of sea transportation that Lighthouse implies. Consider these titles and this theme part of my proposal.

Side note: NEO Lighthouse is a proposed title because the goal of a lighthouse is to draw attention to certain points. They're also only active during times when there's a moon. By no means does it have to be the final title, but I do like it and the opportunities it brings.

---

# Previous proposal:

**All comments below the OP following up to the comment containing the new proposal (https://github.com/neo-project/neo/issues/333#issuecomment-412066474) (also described above) are referring to the NEO 2.5 milestone title proposal. Everything thereafter _should_ refer to the new proposal of _**NEO Lighthouse**_**

```
As the NEO community is currently very unclear on that NEO 2.x is to have many important updates and features, and that NEO 3.0 will be a version that deprecates some of NEO 2.x's features (hence the 3.0 versioning), I propose the creation of the **NEO 2.5 Milestone**.

**Proposals:**
* Create a **NEO 2.5** milestone in this Github repository containing all planned updates that are to be applied to the current version, which will also be compatible with NEO 3.0. Only put non-backwards compatible progressions in the NEO 3.0 milestone.
* Publicize & communicate to the public that the series of updates which are to be included in the current chain fall under the NEO 2.5 milestone, along with the information that NEO 3.0 is a release coming after 2.5, versioned as 3.0 because of technical deprecation (semantic versioning).
* In any discussion/proposal/issue, refer to the "next NEO release" as NEO 2.5. Only refer to NEO 3.0 as the non-backwards compatible version that comes thereafter.
* Make separate issues for each proposal made by @anthdm in https://github.com/neo-project/neo/issues/327#issuecomment-409374792 and include them as part of the NEO 2.5 Milestone
```

This would make it clear to many people (in and outside of the NEO developer community) that there will be plenty of technically impactful and productive updates which are to be deployed prior to the release of NEO 3.0, and would eliminate any further speculation that the next major update will take 2 years.

**Comment by f27d** [comment]
Makes complete sense based on semantic versioning and most people will get it intuitively. We should so some press/comms around it too outside of just Github milestones though

**Comment by deanpress** [comment]
Ye @f27d, that's what I'm implying in my 2nd and 3rd points in the OP

**Comment by phetter** [comment]
Pardon me if overstepping bounds, but I think to really ensure these requirements are observed there should be a singular project lead on the milestone process. If there isn't, it is likely the community will shard and sprawl as it has in the past. It seems the milestone process, as an official project, would help too.

**Comment by canesin** [comment]
Shouldn't we just continue 2.8, 2.9, 2.10 ... And try to semver for once ? It will be super weird to have neo 2.5 coming after 2.7.

**Comment by canesin** [comment]
In my view we don't have to do either, if next version of NEO is released as 2.8 and contains a list of new features we are already doing it. What cannot happen is we continue to have new versions being created without milestones and no release notes.

**Comment by aar0nh0ng** [comment]
The creative naming gives an exciting feeling to the whole thing.
I personally feel that Dean's naming gives a _futuristic feeling_.

It will also help set a branding theme for upcoming marketing efforts and strategies.

Just my 0.02 :)

**Comment by desertrat10** [comment]
I agree with @canesin on this one. As a branding and marketing professional, I feel that this is a "mashing up" of brands/identities. Taking "NEO Matrix" theme and pairing it up with lighthouse (or a beacon type theme) is a mashup of identities and over time, it muddies the waters of the core brand. I'm assuming NEO has a brand identity document in place as a compass for these discussions, right? 

In my professional opinion, I feel that sticking with the core NEO brand and adding versions onto it, 2.5, 2.8, etc. is the cleanest and a minimalist approach to the evolution of the brand itself and keeps the community grounded in a "NEO is growing incrementally with new versions", rather than "NEO is seeking to recreate itself". What any rebrand does is place doubt (sometimes subconsciously) in the user's mind because they feel the company is rebranding. And adding a new theme into the existing brand itself and all future communications does cross into the realms of rebranding. 

Just my 2 cents. ;)

**Comment by ThomasLobker** [comment]
We should have a 2.9 milestone, and maybe already a 2.10 milestone for future functionality that won't make it to the next version. I don't like the names though, for me just the version number would be sufficient and cleaner than some confusing lighthouse name.

**Comment by Ethour** [comment]
I'm not a dev, so it would be useful if I could read that the final release of NEO 2.XX, called NEO "e.g. Lighthouse" will contain a list of features/improvent. In the meanwhile by devs side, you can continue to call the single improvement NEO 2.XX

**Comment by rdgrabowski** [comment]
In the past, it has been hard for me to keep up with names of roadmap milestones and project updates. I understand the value behind creating a brand image, but NEO derives its value from a community that builds. Sticking with that 'brand' of a community that builds, NEO 3.0 would expand upon the foundations of its previous whitepaper releases: 

1. Antshares 1.0
2. NEO 2.0. 
3. NEO 3.0 (tbd)

Sticking with the NEO x.x theme signals the project devs are continuing to build on the original vision, its updated iteration, and the conversations that are ongoing to get NEO to 10k tps plus other goals. 

There are other ways to shift community outreach, that can highlight progress made, without needing to implement a surface level re-naming (i.e. interviews, writeups, conversations, etc). Marketing efforts can display new and current project deliverables, in addition to progress being made on 3.0 behind the scenes. The content is there!

**Comment by syedasifraza** [comment]
In my opinion non-dev people don't know that what is going behind the versions, but I think they can get better idea from theme and it can give a better understand and a positive impression to overall project. Neo Lighthouse looks a great and visionary theme.

**Comment by CaterinaZhang** [comment]
despite the naming, i think it is needed to list all the road map items covered under the span of NEOLighthouse. and the estimated timeline as well. then we can create a task list including documentation, educational blogs, posters, videos, ad, etc.

**Comment by rdgrabowski** [comment]
> list all the road map items

This is something that can give the investors something tangible to look towards.

> then we can create a task list including documentation, educational blogs, posters, videos, ad, etc.

100% agreed, Caterina.

**Comment by Edgegasm** [comment]
Can any developers help contribute to a list of roadmap items for NEO 3.0? I'll start us off:

- Consensus Improvements (Updates to dBFT or alternative mechanisms)
- Fallback consensus mechanism (Through backup consensus nodes or alternative mechanism)
- Node Improvements (neo-sharp, neo-go etc)
- Voting system update
- NeoVM updates (HyperVM?)
- Token standards (Resolve the NEP-5 issues, consider an NFT standard)
- Pricing model update (system fees)
- Anti-spam mechanism (transaction fees, PoW etc)
- Tokenomics Update (maintaining indivisible NEO, GAS distribution improvements etc)
- Additional compilers for NeoVM (New language support, perhaps even a Solidity compiler?)
- Improved documentation for both core infrastructure & smart contracts
- _NeoX, NeoFS, NeoQS etc (probably outside the scope for NEO 3.0 but added anyway)_

Anyone have anything else that should/could be included here? Then we can begin exploring the design choices required for each point, and get a better idea for the scope of NEO 3.0. At that point, we can simplify concepts so that investors/community members can offer their thoughts on key decisions. 

We should also be able to isolate changes that can be applied to NEO 2.x, and which changes will be entirely new for NEO 3.0. That way we can keep the community informed about what updates can be expected on MainNet prior to the conclusion of NEO 3.0.

**Comment by Ethour** [comment]
Thanks for tour post @edgegasm! In which point is the TPS improvement included? 

Could anyone add to each point NEO 2.XX or NEO 3.0?

**Comment by Edgegasm** [comment]
@Ethour I believe TPS will improve as a natural consequence of multiple changes. Consensus improvements being the big one, but I think NeoVM and node changes will also effect this).

**Comment by syedasifraza** [comment]
@Edgegasm 
Is there any plan of user-friendly names instead of addresses in NEO 3.0? and what about account's permission management systems?

**Comment by CaterinaZhang** [comment]
Following @Edgegasm 's wrap up of roadmap list...

Some of the updates will be applied to NEO2.X while others will be applied to NEO 3.0. I've put remarks and re-arranged the listing in below. 

Updates for **NEO2.x**
- Node Improvements (neo-sharp, neo-go etc)
- Token standards (Resolve the NEP-5 issues, consider an NFT standard)
- Anti-spam mechanism (transaction fees, PoW etc)
- Additional compilers for NeoVM (New language support, perhaps even a Solidity compiler?)
- NeoX, NeoFS, NeoQS etc (probably outside the scope for NEO 3.0 but added anyway)

Updates for **NEO3.0**
- Consensus Improvements (Updates to dBFT or alternative mechanisms)
- Fallback consensus mechanism (Through backup consensus nodes or alternative mechanism)
- Voting system update
- NeoVM updates (HyperVM?)
- Pricing model update (system fees)
- Tokenomics Update (maintaining indivisible NEO, GAS distribution improvements etc)
- Improved documentation for both core infrastructure & smart contracts

Please feel free to add in if there's any item missing. **The development of above items does not necessarily follow any specific order**. **it may happen simultaneously. The final milestone is NEO 3.0.** 

Right now there are discussions/debate going on in github for each item . I think it is necessary to sum up the different opinions for each item/topic. In this way, it may help NGD have a better overview and more efficient decision making in order to draft the final whitepaper of NEO 3.0.

**Comment by Grace-Gui** [comment]
Personally I think the branding's function is to highlight certain characteristic or for people to easily remember some new ideas. If NEO 2.x is to be renamed, it may be good for marketing promotion to some extent. However, NEO 2.x is widely used for development for a long time and the name is more easily for developers to refer to. And for the moment, there is no milestone new characteristic. If we create a new name not related to certain function or specification, just to create new topics, it may be distracted and confused. 

I know NEO 3.0 may take a long time to implement. Before that a specific project name may provide more imagination or attract more attention to development of NEO 2.x. But a clear road map may be more helpful in this case. Or if those coming development have common characteristics, then the rename will be more meaningful.

**Comment by toghrulmaharramov** [comment]
@Edgegasm your roadmap list looks great, but I would scrap NeoQS entirely from the list. No one is currently working on NeoQS and there will be no use for quantum-safe cryptography for another 20 years. NeoQS is a marketing ploy and nothing more.

**Comment by Edgegasm** [comment]
@syedasifraza Not as part of NEO core. User friendly names are being implemented by [NNS]([url](https://neons.name/index_En.html)) with an address mapper. If NEO wallets/exchanges implement NNS compatibility, all NEO users will be able to use  .neo names instead of public keys.

As for permission management, the simple answer is no. NEO is not being developed as a centralized, governed blockchain like EOS. Your private key is your own, it's not as a pseudo-account that some ultimate authority can manipulate, so that also means no granting limited permissions to others.

**Comment by deanpress** [comment]
@CaterinaZhang @Edgegasm Please note that this proposal is for the marketing of progressions happening around NEO 2, **not NEO 3**. As @Grace-Gui said, NEO 3.0 is a long while away. People are concerned that there won't be anything exciting happening around NEO for the coming 1-2 years (when NEO 3.0 is supposed to be done).

@Grace-Gui I'm not looking to rename NEO 2, but rather to give a covering project title for everything happening _around_ NEO 2 e.g. NeoFS, NeoID, NEPs, new third-party projects and dAPps, events, communications, marketing and educational material etc.

**Comment by Edgegasm** [comment]
@deanpress I know, just wanted to make sure we had an idea for all elements that will go into NEO 3.0 so that we can see which can be focused for 2.x development/marketing.

**Comment by Grace-Gui** [comment]
I think the reason why we raise this topic is because we announce the NEO 3.0 idea too early to the public, and increase high expectation however to find out it still takes a long way to go, which discourage people. As we all know, NEO 3.0 will be a milestone for NEO, dramatically increase performance of the platform and get NEO prepared for larger scale enterprise use cases, boosting NEO to a new stage. If we announce the news shortly before its realization or disclose progress periodically, it will surly be a good news for all NEO supporters. It may be too rush to announce it when we start to implement the NEO 3.0 at the very beginning. 

But we all know, NEO always has original and revolutionary spirit, which push us to move forward from NEO 1.0 (AntShares, serving as a platform for digitization of assets)  to NEO 2.0 (rebranding as NEO, with the aim of serving the vision of a smart economy), and then will to NEO 3.0 (our vision remains the same, but we want to improve the capability of the platform to serve that vision, particularly for large-scale commercial applications). We keep thinking of how to be the best public blockchain in the world and taking actions. To our great relief, we have a strong, supportive and united community to help us realize the goal. So we choose to share our big vision at the beginning. We want more people to know what NEO will be like in near future, get excited and struggle to realize the big dream together with us. But the announcement decision may not be mature enough to avoid negative underlying premise, e.g.  NEO 2.x may be perceived as a step back from NEO 3.0. This is absolutely what we don't want. 

Also thanks to our enthusiastic community, like @deanpress to help us think of better ways to come up with proposal to eliminate adverse effect, which is really appreciated. NEO is a community based project. We cannot go so far without community support. 

However, as to the rename proposal itself, I may have different opinions. I don't think create a new name for NEO 2.x is necessary. The problem here is people may be confused before NEO 3.0 is officially launched since we are developing NEO 2.x. Due to uncertainty, it may lower their enthusiasm of development. So the substance is a communication problem, not a brand or naming problem. If so, a clear roadmap, instant news release on development progress, and deeper educational may be more helpful. Development is a sustainable movement, and developers will always be happy when achieve great progress, e.g. higher TPS. I don't know if developers will be frustrated if their achievement is not so big compared to the ambitious goals, but I hope not. As Erik has mentioned, improvements that are compatible with NEO 2.0 will also be merged into NEO 2.0 first, so we will continue to see NEO improvements while 3.0 is pursued. Take a metaphor, if NEO is a product like iPhone, we are designing iPhone X, but we are also designing iPhone 8Plus. We look forward to iPhone X, but we may like iPhone 8Plus's new functions before iPhone X is released. It's not in a conflict. I think steady development progress and timely information disclosure will be more conductive to rebuilding confidence. 

On the other side, it may be quite confusing when we take a new name for NEO 2.x. People may have a misunderstanding we have a new project, which is not the case. Also sticking with numbers with clear documentation on new features for each number is better for developers to refer to. If we want more people focus on the development progress we make nowadays, it may be a better way to think of a code name for NEO 3.0 as a secret weapon for NEO. Code name is usually cool for new ideas, which will not cause any confusion. And the code name can be linked to the characteristic of NEO 3.0. If in this way, we will be earnestly keep developing while contribute to our bigger dreams. 

BTW, we may also need to think about better marketing or branding strategy to better promote our progress made or will be made. It's always happy to discuss and inspire great ideas.

**Comment by deanpress** [comment]
>To our great relief, we have a strong, supportive and united community to help us realize the goal. 

The community is now in collective movement to put in an effort with NEO Lighthouse, thanks to the transparency and openness of the initiative.

Community engagement is already reaching new highs due to this initiative, so from an objective standpoint this is exactly what we need and it should be applauded and motivated.

---

>[...] a clear roadmap, instant news release on development progress, and deeper educational may be more helpful

That's what we aim to do with NEO Lighthouse (make NEO 2 progression easier to digest and positively interpret).

As for the other points (new roadmap and preparing updates internally before they have been publicized): Those points are primarily dependent on NGD efforts, and nothing is withholding NGD from doing this. The community can put in effort to promote the platform to the best of their ability, and so can NGD.

CoZ also recognizes that better marketing is needed and are therefore hiring a marketing maintainer.

---

>BTW, we may also need to think about better marketing or branding strategy to better promote our progress made or will be made. It's always happy to discuss and inspire great ideas.

I definitely agree this is a point for NGD to improve on, and it can happen at the same time with the community effort into NEO Lighthouse. This GitHub issue is not the place for that, though. People do have a Discord channel `#branding` now for sharing and brainstorming about this.

---

> it may be a better way to think of a code name for NEO 3.0 as a secret weapon for NEO

The NEO 3.0 premise has already gone too far. Compensating it by bringing even more attention NEO 3 will in turn only make people more concerned about NEO 2.

Look at tweets about NEO and you'll notice a large percentage says something like "who cares about NEO. It's going to take them 2 years to update".

 We need to bring positive attention to NEO 2. That's the focus of this issue.

**Comment by tjs1234** [comment]
We just need to be honest with the community and tell them that NEO 3.0 was announced a bit to early, whose decision was it to release this news??? The hype train is not what the community wants, they want clear, and honest developments of the technology. Explain to the holders how what you are working on will benefit them, is this increasing tps? Is it making it easier to develop with? More secure?  Personally, as an investor and not a developer, I want updates on the major roadmap stops for NEO: neoqs, neox, neoid(we need update on this!!!!), neofs, voting (we need an update on this) as of right now it is very unclear what is being worked on and by whom???

**Comment by Edgegasm** [comment]
NEO 3.0 wasn't announced too early, we just weren't clear about what happens to the current platform on the way there. That's what NEO Lighthouse is created to solve. We can bring all upcoming updates under one banner, and explain the purpose and benefits of each.

**Comment by the-sky-i** [comment]
> We just need to be honest with the community and tell them that NEO 3.0 was announced a bit too early, whose decision was it to release this news???

@tjs1234 Are you serious?? We all know that Caterina Zhang is the director of marketing. So it's very obvious that this decision is among her marketing strategy.
***
> I think the reason why we raise this topic is because we announce the NEO 3.0 idea too early to the public, and increase high expectation

@Grace-Gui got the point. The big and repeated announcements of NEO 3.0 at the beginning rather than the almost ending was a totally **terrible** marketing strategy. Made big announcement of announcement and then announced nothing. Took our expectation to the moon then threw it to the ground. 

It's just like a replay of "three blessing" nightmare, even its promotion trick is the same.

Last time, we created a Fred Gate. **This time, the Caterina Gate is heavily needed to be set up.**

***
Because of the misleading marketing strategy, the community pays too much attention to the future illusion rather than current development. We want to turn the spotlight towards NEO 2 and the current updates. This is why we start this whole discussion. 

The original intention is good but **the method of rename is absolutely improper.** 

It's not only a harm to NEO with two brands but also a disaster of recognization. The first impression of NEO Lighthouse (or other names) to most people, is a new dapp or new project built on NEO instead of reports of NEO 2.x updates. It may spread many confusions to others. 
Besides, the traditional way with the increasing number of 2.x shows that the development is really in progress!

Despite the new name, what we really need is a **roadmap** or a **task list** of future development. It's no need to make every update ahead of time but necessary for community to aware where we are. So a clear to-do list and regular reports of current updates will be enough for community to keep in pace. 

If we really want a new name, it could be a release name for NEO 3.0 while NEO 2.x is completed.
***
So please stop talking about the unnecessary and confused "new name" mask, and focus on asking what we really need, the roadmap and regular reports. 
Still, purpose and benefits explanation can be attached.

**Comment by rdgrabowski** [comment]
> what we really need is a roadmap or a task list of future development. It's no need to make every update ahead of time but necessary for community to aware where we are. So a clear to-do list and regular reports of current updates will be enough for community to keep in pace.

Even a "percentage complete" type of graphic, which shows progress made on @Edgegasm's and @CaterinaZhang's posts would go a long way to assuage the investor community. The graphic can be updated monthly or bi-monthly, and would be a tangible focal point to send folks who might question the progress made on NEO 2.x and 3.0

**Comment by saltyskip** [comment]
@CaterinaZhang 's list seems very clear on what the major tasks that need to be accomplished, whether it is under a moniker of NEO 2 or NEO 3 seems irrelevant. 

All of those tasks should have links to the relevant GitHub issues or projects associated with them.

I generally agree with @the-sky-i 

We don't need fancy names or a clear divide between what goals are for NEO 2 and what goals are for NEO 3 since the lines are blurred. Incremental progress, clear task breakdowns, and project status are better for marketing a serious project.

**Comment by CaterinaZhang** [comment]
> Even a "percentage complete" type of graphic, which shows progress made on @Edgegasm's and @CaterinaZhang's posts would go a long way to assuage the investor community. The graphic can be updated monthly or bi-monthly, and would be a tangible focal point to send folks who might question the progress made on NEO 2.x and 3.0

this was what i was thinking about. Infographic of a "percentage complete" with monthly/bi-monthly updates. that's a must have.

**Comment by CaterinaZhang** [comment]
> @tjs1234 Are you serious?? We all know that Caterina Zhang is the director of marketing. So it's very obvious that this decision is among her marketing strategy.

Thank you for the expectation. i'm not in the position of making such/any strategy alone. anyhow, i do think it's a good approach that NGD invites community to discuss about proposals for NEO3.0. What we are trying to do now is to let more people understand the development progression to reach this milestone.

**Comment by deanpress** [comment]
@the-sky-i The name "NEO Lighthouse" would not be applied as NEO 2.0. It's meant as a working project title for a community effort into bringing attention to NEO 2. So the versioning would be as is. Think of it as a community resource. 

**However**, right now NEO nodes are running on the mainnet with the versioning `3.0-preview`, which turn out to be  2.x nodes with incorrect version names. Ironic considering the active discussion we've having regarding versioning and working titles these past few days.

**Comment by lock9** [comment]
Hello @neo-project/core should we close this?
