### ISSUE TITLE
Question about Verify OnTransaction 

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#429]
Today I have been also spent the day reflecting about AddTransaction with `false` or `true` (#425 )and when call each of them:

In particular, I was thinking about this Verify here: https://github.com/neo-project/neo/blob/c2d7bd44142e3740b878c8feb86ac05d930cf5c5/neo/Network/P2P/Payloads/Transaction.cs#L253
This aforementioned line is called when the Backup does not have a given hash and asks for it (`OnTransaction`). In this case, the transaction is also verified: https://github.com/neo-project/neo/blob/c2d7bd44142e3740b878c8feb86ac05d930cf5c5/neo/Consensus/ConsensusService.cs#L346
My doubt was related to the order that it is verified, because it is verified against `Snapshot snapshot, IEnumerable<Transaction> mempool`, which is `context.Transactions.Values`: https://github.com/neo-project/neo/blob/c2d7bd44142e3740b878c8feb86ac05d930cf5c5/neo/Consensus/ConsensusService.cs#L38
Thus, I was thinking if the Verify should consider the order that this transaction is included (the correct order is the sorted one, right?) or it does not matter? Because some time ago we were discussing about how Storage states changes according to the order that Transactions are processed sequentially.

**Comment by igormcoelho** [comment]
Vitor, I just noticed that `Verify` depends on transactions on the pool... I believe this is a mistake for two reasons: (1) transactions should be independent (2) mempool can be huge, and heavily penalize tx execution.

These lines should be removed in my opinion, otherwise most tx can be blocked during execution:
https://github.com/neo-project/neo/blob/c2d7bd44142e3740b878c8feb86ac05d930cf5c5/neo/Network/P2P/Payloads/Transaction.cs#L260-L261

The best approach in my opinion is to update mempool only when a new tx enters, and if necessary, remove from mempool conflicting tx.

**Comment by erikzhang** [comment]
Transaction verification is order independent.

**Comment by vncoelho** [comment]
I was trying to think about a case in which the Storage would influence the other transactions. I need to reflect about this again.

Thanks, Igor and Erik.
