### ISSUE TITLE
Congestion flow

### ISSUE THREAD

**Issue by jibbah777** [neo-project/neo#448]
Any transactions with multiple recipients per tx  such as tha with nns should be contraflowed into the next several blocks or cap amount of recipients per tx

Ill get my coat if this isnt a viable option or makes no sense

**Comment by jsolman** [comment]
NNS is a NEP5 token, so I don't think it can have have multiple recipients as NEP5 protocol is from one address to another. I think this was another issue of the network spamming of free transactions that is fixed by #500. Also I have a discussion on #357 about a proposal for throttling bad actors that still might be beneficial for abusers of low priority transactions.
