### ISSUE TITLE
Seed nodes could get applicationlogs during offline package sync, but external nodes aren't able to

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#588]
Seed nodes could get applicationlogs during offline package sync, but external nodes aren't able to. While the offline package sync is completed, the later applicationlogs could be synced normally.

**Comment by vncoelho** [comment]
Hi @superboyiii, I think that this is an expected behavior.

I suspect that, in the last versions, nodes are not even connecting to other P2P during syncing.

Maybe we could close this one for now. However, fell free to open if you have any new insight about this. This idea here could be useful in some special applications, thus, do not hesitate to reopen if you think about anything else.
