### ISSUE TITLE
Suggest to add restrictions to maximum block time

### ISSUE THREAD

**Issue by i359** [neo-project/neo#600]
If we can't reach a consensus in 5 minutes, we can make a blank block directly, effectively avoiding a long time without block. is it ok ？

**Comment by canesin** [comment]
No, why would a blank block be mined ? That is only consuming resources, increasing complexity and have no reason to be, it doesn't improve liveness.

**Comment by i359** [comment]
How to avoid producing blocks for a long time, maybe 5 or 10 hours without producing blocks?

**Comment by igormcoelho** [comment]
In fact, blocks are currently produced on average 15 seconds. Sometimes external nodes get stuck for hours due to simultaneous block releases at same height, which will be disallowed after dBFT 2.0 is published (very soon). So even when some nodes get stuck for hours, others keep releasing new blocks in time and the network is always kept alive. 
So, an alternative is to keep an eye on multiple nodes, when one gets stuck try to get another living one, while this change has not yet propagated to mainnet nodes.

**Comment by i359** [comment]
@igormcoelho, thanks for your clarify !
