### ISSUE TITLE
why use akka.net for p2p?it is slow.

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo#611]
akka.net remote translate speed is about 40M/s,it is not a very good number.
and akka.net 's actor ontell is in single thread,it is not very good for performance.

**Comment by vncoelho** [comment]
Sounds worth discussion.
But we should notice that after Akka code was hundreds times faster, so, it came with several improvements.

In this sense, I agree with you Lights, it is always time to wonder. Minor things can always be changed.

**Comment by lightszero** [comment]
NEO use akka.net on lots of modules. i just think is there akka.net is right for p2p.
I will do some test project to show some numbers.

**Comment by shargon** [comment]
any news @lightszero?

**Comment by shargon** [comment]
ping @lightszero

**Comment by lock9** [comment]
Hi @lightszero, can we close this and reopen once we have a proposed solution? It is because I don't see us dropping in the next months

**Comment by Tommo-L** [comment]
We will test it, and we also can consider this library https://libp2p.io/

**Comment by vncoelho** [comment]
This library looks interesting, would this work embedded with the actors or it would replace P2P Akka actors?

**Comment by Tommo-L** [comment]
Currently, @eryeer is testing akka.net and this library. The test report will be generated later.

**Comment by igormcoelho** [comment]
@Tommo-L great idea to use a third-party consolidated library... I took a look at libp2p a while ago. Since it's sponsored by IPFS project, I wondered if that was a good strategical decision... but if it's good enough, let's use it. Another issue I see now is that it doesn't have a C# and C++ implementation (wat???). So, we could take a look at its specification, to see if it's better than ours (more organized/general yet possible to personalize to our case). Let's weight pros and cons. If we build a C# libp2p and use it on Neo, it may be a good contribution to blockchain ecosystem in general (as long as spec of libp2p is good enough). 

One thing bothers me a lot: how is it possible that we don't have a good p2p open-source library, in all this blockchain jungle? I've tried to find a good one already, but couldn't until now...

**Comment by shargon** [comment]
First we can test the difference between a tcp transfer of 100mb with and without akka?

**Comment by eryeer** [comment]
#1106

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/75457300-19ebc800-595b-11ea-906f-3412f43d3a4a.png)

I believe it will be fixed now, @lightszero.
Check https://github.com/akkadotnet/akka.net/issues/2378#event-3071191410

They just closed 2 days ago.

Time to update Akka.
