### ISSUE TITLE
Accessing current View Change Number via RPC.

### ISSUE THREAD

**Issue by saltyskip** [neo-project/neo#629]
Is there a way to access what the current View Change Count is in a give block, as well as the total number of rounds necessary in a historical block via a method like RPC.

This would be useful for improved monitoring of the NEO blockchain, as well as being able to do analysis later on why certain blocks required many view changes

**Comment by vncoelho** [comment]
Hi Andrei, you can use a normal node and start consensus for monitoring messages.
We could design a plugin focused on that, in which a node would monitor follow messages and display, we could even try to do that completely in the frontend, if we were able to join the C# P2P protocol.

**Comment by vncoelho** [comment]
#482 will probably help us in this task, @shargon told us that it was almost finished.

**Comment by igormcoelho** [comment]
Andrei, the easiest way to do so, is by calculating the time taken by each block... around 15s is view 0, 30s view 1, 60s view 2, 120s view 3... and so on.
The actual view is never stored on the blockchain, because it's unnecessary for blockchain persistance, it's just part of the **current** BFT consensus protocol.

You can monitor every type of node messages on real-time by connecting your own node to the main network, so we could perhaps store this information for future usage... I don't think someone is currently publicly cataloguing this, but I agree this is nice information for analysis.

**Comment by saltyskip** [comment]
Thanks guys this answers my question. I will close this issue
