### ISSUE TITLE
CN Timeout bonifications

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#664]
**Proposal:**
Increase timeout with a fixed static value (based on blocktime) for each successful message received.

**Motivation:**
Avoid timeout when the CNs are running on normal operation.

**Negative impacts**
A minor negative impact on `change view` timeout synchronization.

However, it will not affect liveness due to the nature of the agreement using the exponential formula, which will not be affected by fixed increments.

**Details**

* When a node receives `OnPrepRequest` it will increase its timeout by, for example, `ceil(blockTime/10 * 1)`;
* When a node receives a `OnPrepResponse` it will increase its timeout by, for example, `ceil(blockTime/10*2)`;
* When a node receives a `OnCommit` it will increase its timeout by, for example, `ceil(blockTime/10*3)`;

This will ensure that nodes are going to delay a little bit more to timeout when CNs are "supposedly" running normally.

What do you think, @erikzhang, @igormcoelho, @shargon, @jsolman?

**Comment by vncoelho** [comment]
@igormcoelho, what do you think? Should this still be left open? Maybe it is a worth discussion, in particular, if we consider lower block times, such as #375.

**Comment by igormcoelho** [comment]
In fact, I think we should try not to change timing, because these timers are essential to the workings of BFT. However, your idea is very good, when it comes to **protocol changes**. 
Usually we have two protocols: the good case; and the changeview case. If you are in the good case, and **just** evolved one stage (sent a prepare response, commit, etc), I think we can pospone the protocol change by a few milliseconds (perhaps 10% of time 15, which is 1,5 secs).

Example: we just received a prepare response and sent a commit... the timer expires 10 milliseconds later. It makes no sense to just issue the changeview. However, we could issue a fast clock that would expire in at most 1,5 seconds, with the protocol change message (changeview). So, if this clock expires and we are still in the same situation, the message is sent, otherwise it is not sent and discarded.

This avoids bizarre situations where all seem normal, and still a protocol change is made, delaying even more the whole process. This change should not affect global working on network in a negative (we need to test), because this would only be used in these edge situations (suppose you didn't evolve for long time, so you just set the new clock with time zero, to expire instantaneously).

**Comment by erikzhang** [comment]
This will not cause inconsistency in the timeout of each node, and finally lead to more complicated problems? For example, it is more difficult to change view.

**Comment by vncoelho** [comment]
It will not cause problems @erikzhang.

We limited the bonification to 4*Blocktime, which is equal to view 2.

View change request will work normally for those that did not receive any package.
On the other hand, for those that have faith in the current block being generated they will delay a little bit more.

There is an important principle, which is:
    * If no PrepareRequest is produced this bonifications will not be activated (thus, change view will not be affected).
    * If a PrepareRequest is produced, those who receive it will have a minor delay in asking for change view. This delay increase as Network progress.

**Comment by igormcoelho** [comment]
As long time changeview is exponential, things will work perfectly with guaranteed liveness.
If primary speaker completely fails, this won't interfere in timings, because no one will receive PrepareRequest, Response or Commit. When everything is fine, everything will receive these messages and changeview won't be necessary anymore. If network is delayed, which is usually the case, some nodes will actually changeview before other nodes, like you said. Theoretically, this could make consensus happen in higher views, but on practice (with real delays), I doubt that any existing scenario will lead to this, because most of our problems can be solved by precisely waiting "just a little bit" before timeout. Byzantine nodes cannot use this for attack, because they could only attack by providing advancing messages to the network, in other words, attacking it by making it progress. So, I expect that all practical experiments will lead us to the same conclusion, that this proposal is very beneficial to the network.
