### ISSUE TITLE
Smart Services

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#672]
Currently NEO Smart Economy counts with NEO Smart Contracts. Now, we want to introduce a new concept, "NEO Smart Services". 

With this new feature, NEO Blockchain could allow a contract to be invoked without need for a human being to interact directly with it. These types of contracts will be called "Smart Services".

### How it works

- We could register the contract by SYSCALL (Install or Uninstall service) or when deploy was made. We believe deploy option is better.
- During the generation of a block, it will be verified whether an Smart Service should be invoked  as: `Main('OnServiceCallback',[...])`
- For executing a Smart Service it is required to have enough GAS to cover it cost. Any user could send GAS to the contract at any time.
- The consensus algorithm will perform the validation of all executions carried out.

The existence of Decentralized Services allows to create and manage lot of applications without human interaction.

**Comment by erikzhang** [comment]
If we build a third party service (a website for example), and allow users to send transactions to the service and then store it. When the set timeout expires, the service automatically sends the transaction to the blockchain network. What is the difference between this idea and the third party service?

**Comment by shargon** [comment]
With this we don't need a third party service, you can do it everything decentralized.

**Comment by erikzhang** [comment]
Decentralization is not an end. We must find the benefits of doing so before we decide to do so.

**Comment by igormcoelho** [comment]
Good idea @shargon! I think this is related to a recent conversation with @hugbro https://github.com/neo-project/neo/issues/660

But in this sense I agree with Erik, that although I'd love this feature, extra work performed by the network should be well justified... let's think about it :)

**Comment by vncoelho** [comment]
I like this because Consensus could have a priority list and this kind of contracts could have functions for setting min net fee.
These contracts would be like a guarantee that the blockchain is always going to process that in every block (it would be a strong censorship resistant family of txs!), consensus should always include if contract has gas and fee is enought.

These kind of automatic txs persisting looks interesting for IoT Smart Devices, the core of the future Smart and Digital Cities. ahaehauahau

These kind of txs could even be chosen to be included after all txs or before all txs in every block, which could ensure other properties and  open patha for future possibilities.

**Comment by digimbyte** [comment]
> I think this is a powerfull thing.
> 
> Consensus could have a priority list and this kind of contracts could have functions for setting min net fee. These contracts would be like a guarantee that the blockchain is always going to process that in every block (it would be a strong censorship resistant family of txs!), consensus should always include if contract has gas and fee is enough.
> 
> These kind of automatic txs persisting looks interesting for IoT Smart Devices, the core of the future Smart and Digital Cities. ahaehauahau
> 
> These kind of txs could even be chosen to be included after all txs or before all txs in every block, which could ensure other properties and open paths for future possibilities.

these are some beautiful insights into how it could be setup.
in my case, While I have a contract that is invoked by the user, since it depends on a off-chain server with an RPC hook, the issue is when that service is offline or unreachable.

a situation where the blockchain must have some autonomy over itself is essential for any service, even if its a passive table and each contract has limited schedules 

to clarify, I have raised this #2903 and are looking for additional insights but no-one has put a concrete stance forward on use case and minimizing its footprint on the blockchain
