### ISSUE TITLE
Free tx could fill the "500 tx" limit in one block

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#775]
The free tx limit should be 20 in one block if there're more than 500 tx need to be packaged. But now we made a test by sending 1000 free nep-5 txes in a second and find free tx could fill the "500 tx" limit in one block.

https://neoscan-testnet.io/block/cabcca7f4524d7844d223a899c4689bdb5c38d4aadb8d5486e26cfa5845ea257

![image](https://user-images.githubusercontent.com/38493437/58311223-0abf7300-7e3b-11e9-93c9-9d01f4b8695d.png)

**Comment by igormcoelho** [comment]
This is very strange, because the logic is clear here: `Settings.Default.MaxFreeTransactionsPerBlock`
https://github.com/neo-project/neo-plugins/blob/master/SimplePolicy/SimplePolicyPlugin.cs#L68

The default value is 20 or the configuration value: https://github.com/neo-project/neo-plugins/blob/a72c44813271efcafe0a4fcee2505fae3a3b4716/SimplePolicy/Settings.cs#L23

Filter is passing tests for 20 limit on free tx: https://github.com/neo-project/neo-plugins/blob/master/SimplePolicy.UnitTests/UT_SimplePolicy.cs#L87

So, the only explanation I see is: some TestNet node (specifically this one that proposed this block) is not running standard SimplePolicy plugin, or it has a higher value than 20 on its configuration.
As far as I remember, other consensus nodes will validate if information is correct (no double spending tx, etc) but they won't double-check this policy.
Right now, there are two fixes: (1) make sure the consensus node policy plugin has the correct value on this variable (2) adapt dbft to reject blocks that don't match the local policy. 
(1) is much simpler to handle.

On Neo 3.0 the policy will be part of a shared public contract, as far as I'm aware of, so it will be much clearer which configurations are running on each node.

**Comment by superboyiii** [comment]
@igormcoelho  We found the reason. The default value of LowPriorityThreshold in protocol.testnet.json is 0. The consensus nodes' maintainers use this setting for testnet which made this happened.
![image](https://user-images.githubusercontent.com/38493437/58457323-f0e2a080-8158-11e9-9059-45feac6e6529.png)

**Comment by erikzhang** [comment]
Good news.

**Comment by superboyiii** [comment]
Close!
