### ISSUE TITLE
ledger security risk

### ISSUE THREAD

**Issue by berlinmaster** [neo-project/neo#800]
Hello guys,
when I login with my ledger into my wallet in Neonwallet and then when I logout and just put another ledger into my computer with another recovery word list, I can login into the same wallet, even though the ledger device is another one. only when I attempt to login a second time, then I cant access the same wallet with another ledger.

**Comment by vncoelho** [comment]
Hi @berlinmaster.

Maybe they just forgot to remove the possibility of displaying information of previous logged addresses.
However, I am confident that you are not going to be able to sign anything.

On the other hand, I will close this issue, because it should has been opened in the https://github.com/CityOfZion/neon-wallet repository.
