### ISSUE TITLE
Native Contract - Allow multiplier factor inside policy

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#895]
From [Shargon](https://github.com/neo-project/neo/issues/285#issuecomment-508845625):
We should add a multiply factor inside policy native contract (1 by default). This could allow us to reduce the price without make a new release if the price go "to the moon"

**Comment by igormcoelho** [comment]
I think that all prices should be part of Policy contract... the reason is that, since we will abandon 10GAS fee rule, and all prices are effectively stored on the blockchain too, now all prices may vary as needed. Even small/specific changes are possible now, for example, reducing specific operation costs.
Anyway, the multiplier is a good feature in my opinion, because it's easier to adjust and easy to understand.

**Comment by erikzhang** [comment]
Are you talking about `sys_fee` or `net_fee`?

**Comment by shargon** [comment]
Both of them and `Syscall` prices

**Comment by erikzhang** [comment]
As I said before, `sys_fee` are distributed to neo holders. So it is a part of the protocol. Policy is only applied to `net_fee`. For `net_fee`, actually `feePerByte` is a factor.

**Comment by shargon** [comment]
And for syscalls?

**Comment by igormcoelho** [comment]
I think we should do that for sysfees erik. Store individual operation prices there, so that they can be adjusted in time. If we dont stsrt like this,it will be complicated to change them in the future... if they are stored somewhere in chain storage, its easy to keep track of prices in time (directly on code its not possible).

**Comment by vncoelho** [comment]
I think that a multiplier makes sense, but maybe we could have:
`sys_fees_X`
`net_fees_X`

It would be a dynamic way for consensus to easily increase `net_fees_X` during peak times.
But maybe `sys_fees_X` should be the result of the votes of 50%+ NEO Holders (another voting process :D).

**Comment by lock9** [comment]
I agree that all fees/prices should be mutable, all of them. We can divide into 2 or 3 issues if you guys think this is good. I think this is a very good feature for neo 3

**Comment by igormcoelho** [comment]
We should re-open this in a different format... Erik is right, Policy only applies to network policy (including network fees).

In this case, we would need to propose a contract, perhaps a governance contract, that controls voting and also system fee prices.

**Comment by lock9** [comment]
@neo-project/core  should we close this? I didn't quite understand if this is implemented already or not.

**Comment by shargon** [comment]
I think that is a low-priority issue, we can implement this in the future, but is good to be able to change the fee, or adjust the price one time per year, or every 6 months
