### ISSUE TITLE
Create performance metrics used to benchmark  NEO 3

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#920]
Create performance metrics for:
- Network protocol (Examples: connected nodes, messages per second, RPC response time)
- Consensus Algorithm (Examples: confirmation time, time per block in a faulty network)
- IO (Examples: disk access, read/write per second, import block performance)
- Other (Examples: CPU, memory, etc.)

This issue was initially created as #115. Once these metrics are discussed, we can think in a plugin to capture this information (if needed).

**Comment by vncoelho** [comment]
Good idea, @lock9.
That would be great to have such tools.

We need to define a design for measuring it, I think that @devhawk @PeterLinX @neo-project/core can help us to guide how to design these metrics for having it as an option on NEO3.

**Comment by vncoelho** [comment]
I think that we do not need this for NEO2, really.
It is enough if we are able to monitor NEO3. 

For the Increase TPS issue and milestone we can just check the TPS in a specific condition, if that is really necessary.

**Comment by lock9** [comment]
Hi @vncoelho , the main intent of this issue is to replace #115 with a more concise "description". 
Erik is right, to be able to know that we increased our tps, we need to measure it, therefore, we need benchmark tools to test it and be sure it has improved.
Note: the metrics come before the tools, so we need to know what is important to track before we start adding plugins everywhere

**Comment by Thacryba** [comment]
Hi, I was studying this and I thought of these metrics below that might be useful.
I also put the units of measure that I thought it would fit between parentheses.

- **Network protocol:**
- Connected nodes (int);
- Messages per second (/s);
- RPC response time (ms);
- Number of messages discarded (int);
- Latency (ms);
- Time since last block (seconds);
- **Block properties:**
- Time per block (/s);
- **Consensus Algorithm:**
- Confirmation time (ms);
- Time per block in a faulty network (seconds);
- Time to create a new node after confirmation (ms);
- Payload messages time (ms);
- **IO:**
- Disk access (MB/s);
- Time to commit (ms);
- Read/write per second (/s);
- Import block performance (s, min, h);
- Export block performance (s, min, h);
- Synchronization block performance (s, min, h); 
- Time to Transaction per byte (ms);
- Height transaction (bytes);
- **Other:**
- CPU usage for main thread (%);
- CPU usage for worker threads (%);
- Memory (MB);
- Number of active threads (int);
- Exceptions (int);
- Number of invalid transactions caught on verification (int);
- Number of invalid transactions caught on application (int);

**Comment by lock9** [comment]
I think we could also add the variation between the expected block time (from config) to the actual block time.
