### ISSUE TITLE
Expand supported cryptography primitives to include industry standards

### ISSUE THREAD

**Issue by canesin** [neo-project/neo#972]
Hi,

This can be tagged for NEO3 but might still beneficial to NEO2 projects building like SeraphID, Bridge and Nash.

The request is to add all supported Bitcoin (secp256k1) and Ethereum (keccak256) primitives for encryption, signing and hashing algorithms. In addition to those if possible also add X509v3 RSA primitives to allow to interact with digital identity cards like from Estonia or Finland from smart contracts.

**Comment by igormcoelho** [comment]
@canesin I fully agree, could you support this Issue here on vm? https://github.com/neo-project/neo-vm/issues/176

I believe the best way to do it is to put crypto primitives as neo-vm extensions... this way, it's low level implementation, outside the scope of blockchain interops, but computing extensions. As extensions, these can grow in the future, without harming blockchain states or protocol.

We could draft a NEP for it, what do you think?

**Comment by lllwvlvwlll** [comment]
This could also be helpful for Moonlight.  @birmas

**Comment by lock9** [comment]
@igormcoelho  how these extensions would work? What would happen if someone does not have the extension? Are extensions mandatory for all nodes? So why is it called an extension? Why not add it directly to the NEO VM or use it as an Interop service?

**Comment by igormcoelho** [comment]
The proposed idea for extensions is to extend VM operations in time, without creating new opcodes. Since EXTENSION code is incremental (differently from Interops, which are free on every neo-based blockchain platform), we can control it over time, without needing to version the whole thing.
As long as we reject scripts that try to use unexisting extensions in the present, this won't cause problems to be future, when new extensions are added (this is a simple numeric comparison, but requires tx opcodes to be parsed on node).
